require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
